### ISSUE TITLE
Unnecessary files included in PR

### ISSUE THREAD

**Issue by krrevilla18** [lost-pixel/lost-pixel#272]
### Bug description

On the log, it says

```
👋 Exiting process with 0 found differences & 3 baselines to update
Sending anonymized telemetry data.
```

After this, we are expecting the PR to have 3 new additional baseline images, but the PR includes other files as well.

<img width="287" alt="Screenshot 2023-06-21 at 2 13 05 pm" src="https://github.com/lost-pixel/lost-pixel/assets/120606000/50936632-376c-4923-a16d-61b94cb14342">

Any possible reason why it includes files other than the 3 new additional baselines?

**Comment by d-ivashchuk** [comment]
hey! Which folder are we looking at now? are you using the automatic PR flow to update the images? Lost Pixel will generate all images in the current folder, and in the update mode it will move all of the images from current folder into the baseline folder thus making the baseline update.

Would be useful if you share the workflow file and little bit more info on where are you seeing this!

Thanks a lot!

**Comment by krrevilla18** [comment]
These are from the baseline images folder, we added current and difference images folder to .gitignore

```
      - name: Visual Test
        id: lp
        uses: lost-pixel/lost-pixel@v3.4.1
        env:
          LOST_PIXEL_MODE: update

      - name: Create Pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          commit-message: Update Lost-Pixel baselines
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: ${{ github.head_ref || github.ref_name }}
          branch: "lost-pixel-baselines/${{ github.ref_name }}"
          delete-branch: true
          title: "Lost Pixel updating baselines - ${{ github.ref_name }}"
          body: Automated baseline update PR - lost pixel
          draft: false
```

We have this workflow to run VRT, which creates a PR when the testing fails. In this scenario, we expect it to fail since we added 3 new stories.

```
👋 Exiting process with 0 found differences & 3 baselines to update
Sending anonymized telemetry data.
```

Based on the log, there's no difference on the existing stories. However, after the PR was generated it included other updated images as well.
