### ISSUE TITLE
Folders are creates as `root`

### ISSUE THREAD

**Issue by Maxim-Mazurok** [lost-pixel/lost-pixel#344]
### Bug description

I have followed this recipe: https://docs.lost-pixel.com/user-docs/recipes/lost-pixel-oss/automatic-baseline-update-pr

However, folders are create as root and I'm running into this issue: https://github.com/peter-evans/create-pull-request/issues/783

This fixes the problem:

```
Run ls -alrth .lostpixel
total 2[4](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:10:5)K
-rw-r--r--  1 runner docker   19 Dec 26 08:34 .gitignore
drwxr-xr-x 1[5](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:10:6) runner docker 4.0K Dec 2[6](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:10:7) 0[8](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:10:9):35 ..
drwxr-xr-x  2 root   root   4.0K Dec 26 08:35 difference
drwxr-xr-x  5 runner docker 4.0K Dec 26 08:35 .
drwxr-xr-x  3 root   root   4.0K Dec 26 08:35 current
drwxr-xr-x  3 root   root   4.0K Dec 26 08:35 baseline
0s
Run sudo chown -R $USER:$USER .lostpixel
0s
Run ls -alrth .lostpixel
total 24K
-rw-r--r--  1 runner runner   1[9](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:10:10) Dec 26 08:34 .gitignore
drwxr-xr-x [1](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:11:1)5 runner docker [4](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:12:5).0K Dec 26 08:3[5](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:12:6) ..
drwxr-xr-x  2 runner runner 4.0K Dec 2[6](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:12:7) 0[8](https://github.com/Maxim-Mazurok/maxim.mazurok.com/actions/runs/7328008717/job/19955652396#step:12:9):35 difference
drwxr-xr-x  5 runner runner 4.0K Dec 26 08:35 .
drwxr-xr-x  3 runner runner 4.0K Dec 26 08:35 current
drwxr-xr-x  3 runner runner 4.0K Dec 26 08:35 baseline
```

### How to reproduce

```
on: workflow_dispatch

jobs:
  lost-pixel-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Serve
        run: npm run start-dev &

      - name: Wait for server to start
        run: sleep 5

      - name: Lost Pixel
        id: lp
        uses: lost-pixel/lost-pixel@v3.8.2
        env:
          LOST_PIXEL_MODE: update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: update lost-pixel baselines
          delete-branch: true
          branch: 'lost-pixel-update/${{ github.ref_name }}'
          title: 'Lost Pixel update - ${{ github.ref_name }}'
          body: Automated baseline update PR created by Lost Pixel

```

Using this on a repo with no `.lostpixel` folder

**Comment by d-ivashchuk** [comment]
Alternative you can now also update the images locally while running lost-pixel on docker. 

`npx lost-pixel docker update`

it's a fresh feature so it does not have full page mode support so you might need to tinker your `pagesUrl` with `host.docker.internal` to make sure your app is accessible by lost pixel outside of it docker container

**Comment by Maxim-Mazurok** [comment]
I don't think this will help as I'm running into this issue in GHA, not locally

**Comment by thomasaull** [comment]
Just found this issue since I'm facing the same problem, all generated images belong to the root user. In other Docker related projects I'm using 
```
ENV PUID=1000
ENV PGID=1000
```
in the `Dockerfile` to use another user. However this is probably not the correct way to do it, since `1000` is just the user id of the default user on linux and multiple users would have different ids. 

I guess a solution would be to add this parameters to [`executeDockerRun`](https://github.com/lost-pixel/lost-pixel/blob/main/src/docker-runner/utils.ts)

```
--user $(id -u):$(id -g)
```

**Comment by thomasaull** [comment]
Just found this issue since I'm facing the same problem, all generated images belong to the root user. In other Docker related projects I'm using 
```
ENV PUID=1000
ENV PGID=1000
```
in the `Dockerfile` to use another user. However this is probably not the correct way to do it, since `1000` is just the user id of the default user on linux and multiple users would have different ids. 

I guess a solution would be to add this parameters to [`executeDockerRun`](https://github.com/lost-pixel/lost-pixel/blob/main/src/docker-runner/utils.ts)

```
--user $(id -u):$(id -g)
```

**Comment by d-ivashchuk** [comment]
nice find @thomasaull! happy to accept a PR on this if you have time!

**Comment by thomasaull** [comment]
@d-ivashchuk I could certainly give it a shot yeah. I haven't found any documentation about contributing to the project, did I miss it or is there none?

**Comment by d-ivashchuk** [comment]
we have the contributing guide here - https://github.com/lost-pixel/lost-pixel/blob/main/CONTRIBUTING.md

Try it out and if there are any questions - I am more than happy to help and improve the guide as well in the meantime!

**Comment by nickevansuk** [comment]
Just to add for anyone else facing this issue, the following workaround works (while we wait for a fix)

```
    - name: Create .lostpixel directory if it doesn't exist
      # This is a workaround for https://github.com/lost-pixel/lost-pixel/issues/344
      run: mkdir -p .lostpixel/baseline

    - name: Lost Pixel
      id: lp
      uses: lost-pixel/lost-pixel@v3.16.0
      env:
        LOST_PIXEL_MODE: update
```
