### ISSUE TITLE
Support dynamically passing in url in github action to support Vercel previews in Next.js

### ISSUE THREAD

**Issue by cbrwizard** [lost-pixel/lost-pixel#397]
### Mode

Page screenshots

### Feature description

Hello, we at Streamline have a request about reusing what is built by Vercel in Lost Pixel.

Currently, Vercel builds a preview for each pull request we have. Our github actions such as https://github.com/treosh/lighthouse-ci-action wait for Vercel preview to be built, then take its URL and run lighthouse checks. We prefer this way instead of re-building our Next.js for lighthouse action, so that we don't build our website multiple times during CI, which wastes time and spends extra money on Vercel.

Our example usage:
```yml
    steps:
      - uses: actions/checkout@v3
      - name: Get latest preview URL
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.PROJECT_ID}}
          vercel_team_id: ${{ secrets.ORG_ID}}
      - name: Wait preview deploy to complete
        uses: UnlyEd/github-action-await-vercel@v1.2.43
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://${{ steps.vercel_preview_url.outputs.preview_url }}/something
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          configPath: '.github/workflows/lighthouse/lighthouserc.json'
```

It would be great if Lost Pixel supports it as well. Otherwise current page screenshots functionality is not for us and we will have to use the  Storybook approach.

Thank you!

**Comment by andrzej-woof** [comment]
I haven't tried it but how about passing it as an env variable? 🤔 

```ts
import { CustomProjectConfig } from 'lost-pixel';

export const config: CustomProjectConfig = {
  pageShots: {
    baseUrl: `http://${process.env.VERCEL_PREVIEW_URL}`,
    // ...
  },
  // ...
};
```

```yaml
      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.18.2
        env:
            VERCEL_PREVIEW_URL: ${{ steps.vercel_preview_url.outputs.preview_url }}
```
