### ISSUE TITLE
Automatic PRs try to delete all the screenshots

### ISSUE THREAD

**Issue by FezVrasta** [lost-pixel/lost-pixel#442]
### Bug description

We recently enabled the automatic PR generation, but we noticed anything a screenshot needs to be updated, the PR also deletes all the other screenshots for some reason, resulting in 1 edited file, and X deleted ones.

The generated zip artifact doesn't exhibit the same problem.

### How to reproduce

This is our configuration:

```yml
 lostpixel-visual-tests:
    name: "Visual Regression Tests"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [changes, build-storybook]
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.workflows == 'true' }}
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn
      - name: Install dependencies
        run: yarn workspaces focus frontend
      - name: Download storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-build-${{ github.sha }}
          path: packages/frontend/storybook-static
      - name: Lost Pixel Visual Regression Tests
        uses: lost-pixel/lost-pixel@v3.20.0
        id: lp
        env:
          LOST_PIXEL_CONFIG_DIR: packages/frontend
          LOST_PIXEL_MODE: update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GH_WRITE_TOKEN }}
          commit-message: "[skip ci] update lost-pixel baselines"
          delete-branch: true
          branch: "lost-pixel-update/${{ github.head_ref || github.ref_name }} "
          title: "[Lost Pixel update] ${{ github.head_ref || github.ref_name }} "
          body: Automated baseline update PR created by Lost Pixel
          base: ${{ github.head_ref || github.ref_name }}
      - uses: actions/upload-artifact@v4.4.0
        if: failure()
        with:
          include-hidden-files: true
          name: lost-pixel-artefacts
          path: packages/frontend/.lostpixel/
          retention-days: 5

```

If I run `git status` right before the PR is created I see the files have been deleted for some reason.

![CleanShot 2024-12-09 at 4  07 52@2x](https://github.com/user-attachments/assets/7c43efc5-8a2a-4719-aa1c-66106a981a65)

### Expected behavior

I would expect the diff to only include the edited screenshot, and have the unaffected ones untouched.
